name: VoidWorldPlugin
version: 1.1
main: com.boes.voidworld.VoidWorldPlugin
description: A plugin to generate void worlds.
api-version: 1.21

commands:
  generatevoidworld:
    description: Generates a void world.
    usage: /<command> [worldName]
    permission: voidworld.generate

permissions:
  voidworld.generate:
    description: Allows the player to generate void worlds.
    default: op